# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5de16adfc8a6149cacf78f8245765d1564c2f83642f89da91c78525d1300277b126c33dfc4de38c08e984fcec5f559ea206ba07120279279c8345866888ce7a

test:
  secret_key_base: a0e294ef28ce1097806c95a397ffefc3add55d54b549aa12b35019d7868f83fe92e08a8fcb7ff81d6ad775b465884903eebb36622ecfdcb61d28e22a89ae76c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
